# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-04 11:57
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0005_auto_20161217_1931'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='point',
            managers=[
                ('gis', django.db.models.manager.Manager()),
            ],
        ),
    ]
